### ISSUE TITLE
cache early

### ISSUE THREAD

**Issue by Zolmeister** [Zorium/zorium-seed#38]
don't wait for result to cache

**Comment by austinhallock** [comment]
Also need to fix User.getMe and User.login. If the access token doesn't exist, and there are multiple getMe()s when the page loads, it will try to login multiple times, creating one user per simultaneous getMe

```
    Rx.Observable.defer =>
      if accessToken
        @proxy PATH + '/users/me', {qs: {accessToken}}
        .catch (err) =>
          @login()
      else
        @login()
```

My fix was just to cache the login promise and return that if it exists inside of login
