### ISSUE TITLE
instant results for netox.fetch

### ISSUE THREAD

**Issue by austinhallock** [Zorium/zorium-seed#67]
Problem: when cache invalidating requests are made, the update to all corresponding models is not instant.

Eg. I hit 'claim reward', the button is 'loading...' while the user update request goes through, and changes back to the default state once the request is over. When the request is over, the cache gets invalidated, and GET /me is fetched again. 

This is all correct, but since GET /me is not instantaneous, the user sees a 'Claim reward' button for a split second before seeing the countdown timer. This happens because whether or not to show the countdown timer depends GET /me (nextRewardTime). So it uses the old version (where nextRewardTime is in the past) until the new GET /me finishes loading.

Is there an easy way around this? Ie. how do we update the client immediately, assuming success, before the requests for invalidated caches finish? Do we just update the getMe observable directly with the response of the user update call?

**Comment by Zolmeister** [comment]
no, that is a limitation of `netox`
your best bet would be to update the getMe observable directly, but I doubt that will be easy either and may require adding netox hooks
